### ISSUE TITLE
Mutex

### ISSUE THREAD

**Issue by Bouattitni** [Pistou2/P-32-groupe2-SpicyInvader_Level#5]
ca sert a quoi en fait ?
Merci de me répondre sous les plus brefs délais

**Comment by Piztou** [comment]
CANNARD

ça sert a synchroniser les thread, en français a empêcher qu'un bout de code soit activé plusieurs fois en même temps

**Comment by Piztou** [comment]
Closed because it's Off Topic

**Comment by Bouattitni** [comment]
merci
_backstab_
